# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on:
  push:
    branches: [main]
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Merge
        uses: everlytic/branch-merge@1.1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_ref: 'main'
          target_branch: 'gh-pages'
